"""Helpers for parsing and cleaning Julia stderr output."""

from __future__ import annotations

import re

from judiagent.julia.bridge_types import JuliaExecutionResult

STACKTRACE_MARKER = "\nStacktrace:\n"
INTERNAL_TRACE_PATTERNS = [
    r"PythonCall",
    r"JlWrap",
    r"juliacall",
    r"pyjlmodule_seval",
]

CONDAPKG_NOISE = [
    "CondaPkg Found dependencies",
    "CondaPkg Initialising",
    "CondaPkg Installing packages",
    "CondaPkg Wrote",
    "pixi.toml",
    "The default environment has been installed",
    "[dependencies]",
    "[project]",
    "[pypi-dependencies]",
    "channel-priority",
    "conda-forge",
    "automatically generated by CondaPkg",
]


def parse_error_and_trace(raw: str) -> tuple[str, str | None]:
    """Separate a Julia error blob into ``(message, stacktrace-or-None)``."""
    if STACKTRACE_MARKER in raw:
        msg, trace = raw.split(STACKTRACE_MARKER, 1)
        return msg.strip(), trace.strip()

    match = re.search(r"(.*?)(\nStacktrace:\n.*)", raw, re.DOTALL)
    if match:
        return (
            match.group(1).strip(),
            match.group(2).replace("Stacktrace:\n", "").strip(),
        )
    return raw.strip(), None


def sanitize_stacktrace(
    trace: str,
    exclude: list[str] | None = None,
) -> str | None:
    """Remove internal PythonCall/JlWrap frames from a Julia stacktrace."""
    patterns = exclude or INTERNAL_TRACE_PATTERNS
    kept = [
        line
        for line in trace.splitlines()
        if not any(re.search(pattern, line) for pattern in patterns)
    ]
    return "\n".join(kept) if kept else None


def strip_condapkg_noise(text: str) -> str:
    """Remove verbose CondaPkg chatter from mixed Julia stderr output."""
    if not text:
        return text

    filtered: list[str] = []
    suppressing = False
    for line in text.split("\n"):
        if any(token.lower() in line.lower() for token in CONDAPKG_NOISE):
            suppressing = True
            continue
        if not line.strip():
            suppressing = False
            continue
        if not suppressing:
            filtered.append(line)
    return "\n".join(filtered)


def format_runtime_error(result: JuliaExecutionResult) -> str:
    """Render a readable runtime error string from a Julia execution result."""
    message = strip_condapkg_noise(result.error_summary)
    parts = [message] if message else []
    if result.error_trace is not None:
        trace = strip_condapkg_noise(result.error_trace)
        if trace:
            parts.append(f"\nStacktrace:\n{trace}")
    return "".join(parts)
